train=[
    ('its a horrible day','abuse'),
    ('you are such a pain in the ass','abuse'),
    ('he is such an asshole','abuse'),
    ('you idiot, where were you?','abuse'),
    ('he is such a stupid person','abuse'),
    ('how dare you do that to him, you bastard?','abuse'),
    ('this was done by that scoundrel','abuse'),
    ('that was fucking awful','abuse'),
    ('you have an awful face','abuse'),
    ('blacks can never be believed','abuse'),
    ('these white idiots are such cheats','abuse'),
    ('he is murdering the work that he is doing','abuse'),
    ('you are such a cheat and an asshole','abuse'),
    ('go and get lost in your own creepy world','abuse'),
    ('he is such a creep','abuse'),
    ('you better mind your own business','abuse'),
    ('how dare you do that to him, you bastard?','abuse'),
    ('just get lost from here','abuse'),
    ('all asians are ugly people','abuse'),
    ('americans are all proud fools','abuse'),
    ('i am sick and tired of all your excuses','abuse'),
    ('you are a brainless person','abuse'),
    ('all idiots are living in africa','abuse'),
    ('she has such an ugly face','abuse'),
    ('i cannot tolerate his face anymore','abuse'),
    ('all of them here are such fools','abuse'),
    ('you irritate me a lot','abuse'),
    ('get out my sight','abuse'),
    ('i hate the way you are','abuse'),
    ('do not show me your disgusting face','abuse'),
    ('you must be killed and sent to hell','abuse'),
    ('you are a headache to everyone in here','abuse'),
    ('all politicians are dogs who wait for power and money','abuse'),
    ('all actors are pigs who simply do anything for money','abuse'),
    ('why do you think all nomads looked like dinosaurs','abuse'),
    ('your stupid decision has been a loss','abuse'),
    ('he is as fat as an elephant','abuse'),
    ('how can you do such a dirty trick','abuse'),
    ('she looks just like a donkeys face','abuse'),
    ('it looks good on you','normal'),
    ('this is such an amazing place','normal'),
    ('he is a very sweet person to be with','normal'),
    ('the speech was very inspiring','normal'),
    ('the girl looks very beautiful','normal'),
    ('the building is very magnificient','normal'),
    ('this place is very peaceful','normal'),
    ('he is very intelligent','normal'),
    ('act smart and finish the work','normal'),
    ('he studies well and scores good marks','normal'),
    ('i am very happy on winning','normal'),
    ('i enjoy my job','normal'),
    ('i feel amazing','normal'),
    ('garry is a friend of mine','normal'),
    ('i cannot believe i am doing this','normal'),
    ('i feel very good about these beers','normal'),
    ('i love this sandwich','normal'),
    ('what an awesome view','normal'),
    ('this is my best work','normal'),
    ('the dress looks very pretty','normal')
   ]

test=[
      ('you are such a pain in the ass','abuse'),
      ('he is a very sweet person to be with','normal'),
      ('he is such a creep','abuse'),
      ('the speech was very inspiring','normal'),
      ('you irritate me a lot','abuse'),
      ('how dare you do that to him, you bastard?','abuse'),
      ('all idiots are living in africa','abuse'),
      ('the girl looks very beautiful','normal'),
      ('he is murdering the work that he is doing','abuse'),
      ('the building is very magnificient','normal'),
      ('all idiots are living in africa','abuse'),
      ('this place is very peaceful','normal'),
      ('she has such an ugly face','abuse'),
      ('i cannot tolerate his face anymore','abuse'),
      ('i feel amazing','normal'),
      ('all of them here are such fools','abuse'),
      ('you irritate me a lot','abuse'),
      ('get out my sight','abuse'),
      ('he is very intelligent','normal'),
      ('i cannot believe i am doing this','normal'),
      ('i hate the way you are','abuse'),
      ('do not show me your disgusting face','abuse'),
      ('act smart and finish the work','normal'),
      ('you must be killed and sent to hell','abuse'),
      ('he studies well and scores good marks','normal'),
      ('you are a headache to everyone in here','abuse'),
      ('i am very happy on winning','normal'),
      ('all politicians are dogs who wait for power and money','abuse'),
      ('i enjoy my job','normal'),
      ('garry is a friend of mine','normal'),
      ('all actors are pigs who simply do anything for money','abuse'),
      ('why do you think all nomads looked like dinosaurs','abuse')
    ]
import textblob
from  textblob.classifiers import NaiveBayesClassifier
cl = NaiveBayesClassifier(train)

#cl.classify("he is such a stupid person")

prob_dist=cl.prob_classify("the weather is pleasant")
print(prob_dist.max())

print(round(prob_dist.prob("abuse"),2))
print(round(prob_dist.prob("normal"),2))
